import React, { useState } from "react";
import {
  FREE_CONNECTORS_CATALOG,
  FreeConnector,
  STAGES_CONFIG,
  StageId,
  executeFreeConnectorQuery,
  QueryExecutionResult,
} from "../lib/freeConnectors";
import {
  Search,
  Play,
  Terminal,
  Network,
  Cpu,
  CheckCircle2,
  Key,
  Copy,
  Check,
  RefreshCw,
  Code,
  FileText,
  Wand2,
  Bot,
  HardDrive,
  Star,
} from "lucide-react";
import { motion, AnimatePresence } from "motion/react";
import { useToast } from "./ToastProvider";

export default function FreeSourcesTab() {
  const { showToast } = useToast();
  const [activeStage, setActiveStage] = useState<"ALL" | StageId>("CORE_7");
  const [activeSubFilter, setActiveSubFilter] = useState<"ALL" | "CORE" | "CYBER" | "SCIENTIFIC" | "OSINT" | "GEOSPATIAL" | "FINANCIAL">("ALL");
  const [searchQuery, setSearchQuery] = useState<string>("");
  const [selectedConnectorId, setSelectedConnectorId] = useState<string>("opensanctions_yente");
  const [queryTerm, setQueryTerm] = useState<string>("ТОВ 'СПЕЦІАЛЬНІ ТЕХНОЛОГІЇ'");
  const [isExecuting, setIsExecuting] = useState<boolean>(false);
  const [queryResult, setQueryResult] = useState<QueryExecutionResult | null>(null);
  const [activeResultTab, setActiveResultTab] = useState<"raw" | "er" | "graph" | "vector" | "storage" | "quality">("raw");
  const [copiedKey, setCopiedKey] = useState<string | null>(null);

  // Passport Modal State
  const [activePassportConnector, setActivePassportConnector] = useState<FreeConnector | null>(null);

  // Universal Auth Manager State
  const [selectedAuthProtocol, setSelectedAuthProtocol] = useState<string>("OAuth2");
  const [authConfigModal, setAuthConfigModal] = useState<boolean>(false);

  // Universal Discovery Engine State
  const [factoryDocsUrl, setFactoryDocsUrl] = useState<string>("https://data.gov.ua/api/3/action/package_show");
  const [isGeneratingConnector, setIsGeneratingConnector] = useState<boolean>(false);
  const [generatedCode, setGeneratedCode] = useState<string | null>(null);
  const [schemaDriftActive, setSchemaDriftActive] = useState<boolean>(true);

  // Connectors local state to allow toggling enable/disable (Hot-Reload)
  const [connectors, setConnectors] = useState<FreeConnector[]>(FREE_CONNECTORS_CATALOG);

  const selectedConnector = connectors.find((c) => c.id === selectedConnectorId) || connectors[0];

  const filteredConnectors = connectors.filter((c) => {
    if (activeStage !== "ALL" && c.stage !== activeStage) return false;
    if (activeSubFilter !== "ALL" && c.subCategory !== activeSubFilter) return false;
    if (searchQuery.trim() !== "") {
      const q = searchQuery.toLowerCase();
      return (
        c.name.toLowerCase().includes(q) ||
        c.category.toLowerCase().includes(q) ||
        c.description.toLowerCase().includes(q) ||
        c.endpoint.toLowerCase().includes(q) ||
        c.passport.owner.toLowerCase().includes(q)
      );
    }
    return true;
  });

  const toggleConnectorStatus = (id: string) => {
    setConnectors((prev) =>
      prev.map((item) => (item.id === id ? { ...item, enabled: !item.enabled } : item))
    );
    showToast("Статус конектора оновлено у режимі Hot-Reload", "info");
  };

  const handleExecuteQuery = async (e?: React.FormEvent) => {
    if (e) e.preventDefault();
    if (isExecuting) return;

    setIsExecuting(true);
    try {
      const res = await executeFreeConnectorQuery(selectedConnectorId, queryTerm);
      setQueryResult(res);
      showToast(`Запит успішно виконано через ${selectedConnector?.name || 'connector'}`, "success");
    } catch (err) {
      showToast("Помилка виконання запиту", "error");
    } finally {
      setIsExecuting(false);
    }
  };

  const copyToClipboard = (text: string, key: string) => {
    navigator.clipboard.writeText(text);
    setCopiedKey(key);
    showToast("Скопійовано в буфер обміну", "info");
    setTimeout(() => setCopiedKey(null), 2000);
  };

  const handleRunFactoryGenerator = (e: React.FormEvent) => {
    e.preventDefault();
    if (!factoryDocsUrl) return;

    setIsGeneratingConnector(true);
    setGeneratedCode(null);

    setTimeout(() => {
      setIsGeneratingConnector(false);
      setGeneratedCode(`/**
 * PREDATOR Universal Discovery Engine — Auto-Generated Connector
 * Target Endpoint / Docs: ${factoryDocsUrl}
 * Generated by Autonomous Agent v4.2 with Schema Drift Watchdog & FollowTheMoney Mapping
 */
import { BaseConnector, FtMEntity, SchemaDriftMonitor } from "@predator/connector-sdk";

export class UniversalDiscoveredConnector extends BaseConnector {
  readonly id = "auto_disc_${Math.floor(Math.random() * 8999 + 1000)}";
  readonly name = "Universal Discovered State Registry";
  readonly protocol = "OpenAPI 3.0 / CKAN";
  readonly schemaDriftMonitor = new SchemaDriftMonitor({ autoRecover: true });

  async fetchAndResolve(query: string): Promise<FtMEntity[]> {
    const rawData = await this.httpGet(\`\${this.endpoint}?q=\${encodeURIComponent(query)}\`);
    this.schemaDriftMonitor.checkDrift(rawData);
    
    return this.mapToFollowTheMoney(rawData);
  }

  mapToFollowTheMoney(data: any): FtMEntity[] {
    return (data.results || [data]).map((item: any) => ({
      schema: "Company",
      properties: {
        name: [item.company_name || item.official_name || item.caption],
        registrationNumber: [item.tax_id || item.edrpou || item.registrationNumber],
        jurisdiction: [item.jurisdiction || "ua"],
        status: [item.status || "active"],
      }
    }));
  }
}`);
      showToast("Конектор, JSON Schema та Entity Mapping успішно згенеровані!", "success");
    }, 1600);
  };

  const coreSevenItems = connectors.filter((c) => c.isCoreSeven);

  return (
    <div className="space-y-6 text-slate-200 font-sans pb-12">
      {/* Platform Architecture Header */}
      <div className="p-6 bg-gradient-to-r from-amber-950/60 via-slate-900 to-emerald-950/50 border border-amber-500/30 rounded-3xl relative overflow-hidden shadow-2xl">
        <div className="absolute -right-12 -bottom-12 w-80 h-80 bg-amber-500/10 rounded-full blur-3xl pointer-events-none" />
        <div className="flex flex-col lg:flex-row lg:items-center justify-between gap-6 relative z-10">
          <div className="space-y-2.5">
            <div className="flex flex-wrap items-center gap-2">
              <span className="px-3 py-1 bg-amber-500/20 text-amber-300 border border-amber-500/40 rounded-full text-[11px] font-mono font-bold uppercase tracking-wider flex items-center gap-1.5">
                <Star className="w-3.5 h-3.5 text-amber-400 fill-amber-400" />
                PREDATOR Core Data Layer — "Велика Сімка"
              </span>
              <span className="px-3 py-1 bg-emerald-500/20 text-emerald-300 border border-emerald-500/40 rounded-full text-[11px] font-mono font-bold uppercase tracking-wider">
                Universal Discovery Engine Active
              </span>
            </div>
            <h2 className="text-2xl sm:text-3xl font-black text-white tracking-tight">
              Ядро Екосистеми Збору Даних Світового Рівня
            </h2>
            <p className="text-xs sm:text-sm text-slate-300 w-full leading-relaxed">
              Архітектура PREDATOR Analytics: 7 ключових джерел глобального покриття ризиків, компаній, витоків, судових справ, новин та цифрової інфраструктури + Друга Хвиля інтеграцій та Universal Discovery Engine для автономного підключення нових реєстрів.
            </p>
          </div>

          <div className="flex flex-wrap items-center gap-2.5 self-start lg:self-center">
            <button
              onClick={() => setAuthConfigModal(true)}
              className="px-4 py-2.5 bg-slate-800/90 hover:bg-slate-700/90 border border-slate-700 text-slate-200 text-xs font-bold rounded-2xl flex items-center gap-2 transition-all cursor-pointer shadow-md"
            >
              <Key className="w-4 h-4 text-amber-400" />
              <span>Auth Manager (11 Protocols)</span>
            </button>
            <button
              onClick={() => {
                setSelectedConnectorId("opensanctions_yente");
                setQueryTerm("ТОВ СПЕЦІАЛЬНІ ТЕХНОЛОГІЇ");
                handleExecuteQuery();
              }}
              className="px-4 py-2.5 bg-gradient-to-r from-amber-600 to-emerald-600 hover:from-amber-500 hover:to-emerald-500 text-white text-xs font-bold rounded-2xl flex items-center gap-2 transition-all cursor-pointer shadow-lg shadow-amber-950/50"
            >
              <Play className="w-4 h-4 text-white fill-white" />
              <span>Запустити Велика Сімка Test</span>
            </button>
          </div>
        </div>

        {/* 8-Stage Architecture Pipeline Status */}
        <div className="grid grid-cols-2 sm:grid-cols-3 lg:grid-cols-9 gap-2 mt-6 pt-5 border-t border-slate-800/80 font-mono text-[11px]">
          {STAGES_CONFIG.map((st) => {
            const count = connectors.filter((c) => c.stage === st.id).length;
            const isActive = activeStage === st.id;

            return (
              <button
                key={st.id}
                onClick={() => setActiveStage(st.id)}
                className={`p-2.5 rounded-2xl border text-left transition-all cursor-pointer flex flex-col justify-between h-20 ${
                  isActive
                    ? "bg-amber-500/20 border-amber-500/50 text-white shadow-md"
                    : "bg-slate-950/60 border-slate-800/80 text-slate-400 hover:border-slate-700 hover:text-slate-200"
                }`}
              >
                <div className="text-[10px] text-slate-400 uppercase font-bold truncate">{st.title.split("(")[0]}</div>
                <div className="font-bold text-xs text-amber-400 flex items-center justify-between">
                  <span>{st.id === "CORE_7" ? "7 Джерел ⭐" : `${count} Модулів`}</span>
                  <span className="w-2 h-2 rounded-full bg-amber-400 animate-pulse" />
                </div>
              </button>
            );
          })}
        </div>
      </div>

      {/* CORE DATA LAYER: THE BIG SEVEN HIGHLIGHT PANEL */}
      <div className="p-5 bg-slate-900 border border-amber-500/30 rounded-3xl space-y-4 shadow-xl">
        <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-3 border-b border-slate-800 pb-3">
          <div className="flex items-center gap-2">
            <Star className="w-5 h-5 text-amber-400 fill-amber-400" />
            <h3 className="text-sm font-bold text-white uppercase tracking-wider font-mono">
              Рекомендована "Велика Сімка" (Core Data Layer)
            </h3>
          </div>
          <span className="text-xs text-amber-300 font-mono font-bold">
            Покриття 99.8% ризиків, юридичних осіб, витоків, суду та новин
          </span>
        </div>

        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-7 gap-3">
          {coreSevenItems.map((c) => {
            const isSelected = selectedConnectorId === c.id;
            return (
              <div
                key={c.id}
                onClick={() => {
                  setSelectedConnectorId(c.id);
                  setQueryTerm(c.sampleQuery.split("=")[1] || "ТОВ Спеціальні ТехноЛОГІЇ");
                  handleExecuteQuery();
                }}
                className={`p-3 rounded-2xl border cursor-pointer transition-all flex flex-col justify-between space-y-2 relative overflow-hidden group ${
                  isSelected
                    ? "bg-amber-500/20 border-amber-500 text-white shadow-lg shadow-amber-950/40"
                    : "bg-slate-950/80 border-slate-800 text-slate-300 hover:border-amber-500/50 hover:text-white"
                }`}
              >
                <div className="flex items-center justify-between">
                  <span className="px-2 py-0.5 bg-amber-500/30 text-amber-300 font-mono text-[10px] font-black rounded-lg">
                    #{c.coreSevenRank}
                  </span>
                  <Star className="w-3.5 h-3.5 text-amber-400 fill-amber-400" />
                </div>
                <div className="font-bold text-xs leading-tight font-mono line-clamp-2">
                  {c.name.split("—")[0]}
                </div>
                <div className="text-[10px] text-slate-400 truncate">
                  {c.coreSevenTitle}
                </div>
              </div>
            );
          })}
        </div>
      </div>

      {/* STAGE 1 & UNIVERSAL ARCHITECTURE DISPLAY */}
      <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
        {/* Storage Router Card */}
        <div className="p-4 bg-slate-900 border border-slate-800 rounded-3xl space-y-3 shadow-lg">
          <div className="flex items-center gap-2 text-emerald-400">
            <HardDrive className="w-5 h-5" />
            <h3 className="text-xs font-bold uppercase tracking-wider font-mono text-white">Multi-Engine Storage Router</h3>
          </div>
          <p className="text-xs text-slate-300 leading-relaxed">
            Маршрутизація даних у 5 цільових СУБД:
          </p>
          <div className="space-y-1.5 font-mono text-[11px]">
            <div className="p-2 bg-slate-950 rounded-xl border border-slate-800 flex justify-between">
              <span className="text-slate-400">Компанії / Реєстри</span>
              <span className="text-blue-400 font-bold">PostgreSQL</span>
            </div>
            <div className="p-2 bg-slate-950 rounded-xl border border-slate-800 flex justify-between">
              <span className="text-slate-400">Графи зв'язків</span>
              <span className="text-purple-400 font-bold">Neo4j / Memgraph</span>
            </div>
            <div className="p-2 bg-slate-950 rounded-xl border border-slate-800 flex justify-between">
              <span className="text-slate-400">Документи / Витоки</span>
              <span className="text-amber-400 font-bold">MinIO S3</span>
            </div>
            <div className="p-2 bg-slate-950 rounded-xl border border-slate-800 flex justify-between">
              <span className="text-slate-400">Embeddings</span>
              <span className="text-emerald-400 font-bold">Qdrant Vector DB</span>
            </div>
          </div>
        </div>

        {/* Universal Auth Manager Card */}
        <div className="p-4 bg-slate-900 border border-slate-800 rounded-3xl space-y-3 shadow-lg">
          <div className="flex items-center gap-2 text-amber-400">
            <Key className="w-5 h-5" />
            <h3 className="text-xs font-bold uppercase tracking-wider font-mono text-white">Universal Auth Manager</h3>
          </div>
          <p className="text-xs text-slate-300 leading-relaxed">
            11 протоколів авторизації в єдиному Vault:
          </p>
          <div className="grid grid-cols-2 gap-1.5 font-mono text-[10px]">
            {["API Key", "OAuth2", "JWT", "Bearer", "Basic Auth", "Cookie", "Session", "PAT", "Client Secret", "mTLS", "SSH Keys"].map((m) => (
              <span key={m} className="p-1.5 bg-slate-950 border border-slate-800 rounded-lg text-amber-300 font-bold text-center">
                ✓ {m}
              </span>
            ))}
          </div>
        </div>

        {/* Entity Resolution Engine Card */}
        <div className="p-4 bg-slate-900 border border-slate-800 rounded-3xl space-y-3 shadow-lg">
          <div className="flex items-center gap-2 text-purple-400">
            <Cpu className="w-5 h-5" />
            <h3 className="text-xs font-bold uppercase tracking-wider font-mono text-white">Entity Resolution (FtM)</h3>
          </div>
          <p className="text-xs text-slate-300 leading-relaxed">
            Дедуплікація та злиття аліасів у канонічну сутність:
          </p>
          <div className="p-3 bg-slate-950 rounded-2xl border border-slate-800 space-y-2 font-mono text-[11px]">
            <div className="text-slate-400">Вхідні аліаси:</div>
            <div className="text-slate-300 text-[10px] space-y-0.5">
              <div>• "ТОВ Еліт Бізнес Брок"</div>
              <div>• "Elite Business Brok LLC"</div>
              <div>• "Код ЄДРПОУ: 39281045"</div>
            </div>
            <div className="text-emerald-400 font-bold border-t border-slate-800 pt-1.5 flex justify-between">
              <span>Канонічний ID:</span>
              <span>entity-39281045 (99.8%)</span>
            </div>
          </div>
        </div>
      </div>

      {/* LIVE QUERY CONSOLE */}
      <div className="p-5 bg-slate-900 border border-slate-800 rounded-3xl shadow-xl space-y-4">
        <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-3 border-b border-slate-800 pb-3">
          <div className="flex items-center gap-2">
            <Terminal className="w-5 h-5 text-emerald-400" />
            <h3 className="text-sm font-bold text-white uppercase tracking-wider font-mono">
              Консоль Виконання Запитів та Маршрутизації (Live Pipeline)
            </h3>
          </div>
          <span className="text-xs text-slate-400 font-mono">
            Auto Storage Routing + Entity Resolution + Quality Audit
          </span>
        </div>

        <form onSubmit={handleExecuteQuery} className="grid grid-cols-1 md:grid-cols-12 gap-3">
          <div className="md:col-span-4">
            <label className="block text-[11px] font-mono text-slate-400 mb-1">Оберіть джерело даних</label>
            <select
              value={selectedConnectorId}
              onChange={(e) => setSelectedConnectorId(e.target.value)}
              className="w-full bg-slate-950 border border-slate-800 rounded-xl px-3 py-2 text-xs text-slate-200 focus:outline-none focus:border-emerald-500 font-mono"
            >
              {connectors.map((c) => (
                <option key={c.id} value={c.id}>
                  {c.flag} [{c.stage.replace("_", " ")}] {c.name}
                </option>
              ))}
            </select>
          </div>

          <div className="md:col-span-6">
            <label className="block text-[11px] font-mono text-slate-400 mb-1">Пошуковий об'єкт розвідки</label>
            <input
              type="text"
              value={queryTerm}
              onChange={(e) => setQueryTerm(e.target.value)}
              placeholder="напр., ТОВ Спеціальні Технології, 3129401824, Kovalenko"
              className="w-full bg-slate-950 border border-slate-800 rounded-xl px-3 py-2 text-xs text-slate-200 focus:outline-none focus:border-emerald-500 font-mono"
            />
          </div>

          <div className="md:col-span-2 flex items-end">
            <button
              type="submit"
              disabled={isExecuting}
              className="w-full py-2 px-3 bg-emerald-600 hover:bg-emerald-500 disabled:opacity-50 text-white font-mono font-bold text-xs rounded-xl flex items-center justify-center gap-1.5 transition-all cursor-pointer shadow-md"
            >
              {isExecuting ? (
                <>
                  <RefreshCw className="w-3.5 h-3.5 animate-spin" />
                  <span>Виконання...</span>
                </>
              ) : (
                <>
                  <Play className="w-3.5 h-3.5 fill-white" />
                  <span>Запустити</span>
                </>
              )}
            </button>
          </div>
        </form>

        {/* Selected Connector Passport Summary Bar */}
        <div className="p-3 bg-slate-950/80 border border-slate-800 rounded-2xl flex flex-col md:flex-row md:items-center justify-between gap-3 text-xs font-mono">
          <div className="flex items-center gap-2">
            <span className="text-base">{selectedConnector?.flag || ''}</span>
            <div>
              <span className="font-bold text-white">{selectedConnector?.name || 'Unknown'}</span>
              <span className="text-slate-500 ml-2">({selectedConnector?.passport?.owner || 'Unknown'})</span>
            </div>
          </div>
          <div className="flex flex-wrap items-center gap-3 text-[11px]">
            <button
              onClick={() => setActivePassportConnector(selectedConnector || null)}
              className="px-2.5 py-1 bg-amber-500/20 hover:bg-amber-500/30 text-amber-300 border border-amber-500/40 rounded-lg font-bold flex items-center gap-1 cursor-pointer transition-all"
            >
              <FileText className="w-3.5 h-3.5" />
              <span>Паспорт Конектора (18 Параметрів)</span>
            </button>
            <span className="px-2 py-0.5 bg-emerald-500/10 border border-emerald-500/30 text-emerald-400 rounded font-bold">
              Trust Score: {selectedConnector?.passport?.trustScore || 0}%
            </span>
          </div>
        </div>

        {/* Output Windows */}
        <AnimatePresence mode="wait">
          {queryResult && (
            <motion.div
              initial={{ opacity: 0, y: 10 }}
              animate={{ opacity: 1, y: 0 }}
              exit={{ opacity: 0 }}
              className="space-y-3 pt-2"
            >
              {/* Output Tabs */}
              <div className="flex items-center justify-between border-b border-slate-800 pb-2">
                <div className="flex items-center gap-1 overflow-x-auto">
                  <button
                    onClick={() => setActiveResultTab("raw")}
                    className={`px-3 py-1.5 rounded-lg text-xs font-mono font-bold transition-all cursor-pointer flex items-center gap-1.5 ${
                      activeResultTab === "raw"
                        ? "bg-emerald-500/20 text-emerald-300 border border-emerald-500/40"
                        : "text-slate-400 hover:text-white"
                    }`}
                  >
                    <Code className="w-3.5 h-3.5" />
                    <span>Raw Response</span>
                  </button>

                  <button
                    onClick={() => setActiveResultTab("er")}
                    className={`px-3 py-1.5 rounded-lg text-xs font-mono font-bold transition-all cursor-pointer flex items-center gap-1.5 ${
                      activeResultTab === "er"
                        ? "bg-blue-500/20 text-blue-300 border border-blue-500/40"
                        : "text-slate-400 hover:text-white"
                    }`}
                  >
                    <Cpu className="w-3.5 h-3.5" />
                    <span>Entity Resolution ({queryResult.entityResolution.confidenceScore}%)</span>
                  </button>

                  <button
                    onClick={() => setActiveResultTab("graph")}
                    className={`px-3 py-1.5 rounded-lg text-xs font-mono font-bold transition-all cursor-pointer flex items-center gap-1.5 ${
                      activeResultTab === "graph"
                        ? "bg-purple-500/20 text-purple-300 border border-purple-500/40"
                        : "text-slate-400 hover:text-white"
                    }`}
                  >
                    <Network className="w-3.5 h-3.5" />
                    <span>Graph Cypher</span>
                  </button>

                  <button
                    onClick={() => setActiveResultTab("storage")}
                    className={`px-3 py-1.5 rounded-lg text-xs font-mono font-bold transition-all cursor-pointer flex items-center gap-1.5 ${
                      activeResultTab === "storage"
                        ? "bg-amber-500/20 text-amber-300 border border-amber-500/40"
                        : "text-slate-400 hover:text-white"
                    }`}
                  >
                    <HardDrive className="w-3.5 h-3.5" />
                    <span>Storage Routing</span>
                  </button>

                  <button
                    onClick={() => setActiveResultTab("quality")}
                    className={`px-3 py-1.5 rounded-lg text-xs font-mono font-bold transition-all cursor-pointer flex items-center gap-1.5 ${
                      activeResultTab === "quality"
                        ? "bg-rose-500/20 text-rose-300 border border-rose-500/40"
                        : "text-slate-400 hover:text-white"
                    }`}
                  >
                    <CheckCircle2 className="w-3.5 h-3.5" />
                    <span>Data Quality Audit</span>
                  </button>
                </div>

                <div className="text-slate-400 text-xs font-mono">
                  Latency: <span className="text-emerald-400 font-bold">{queryResult.latencyMs}ms</span>
                </div>
              </div>

              {/* Tab Content Display */}
              <div className="p-4 bg-slate-950 rounded-2xl border border-slate-800 font-mono text-xs overflow-x-auto max-h-80 custom-scrollbar">
                {activeResultTab === "raw" && (
                  <pre className="text-emerald-300 leading-relaxed">
                    {JSON.stringify(queryResult.rawResponse, null, 2)}
                  </pre>
                )}

                {activeResultTab === "er" && (
                  <div className="space-y-3">
                    <div className="flex justify-between items-center text-slate-300 pb-2 border-b border-slate-900 text-[11px]">
                      <span className="font-bold text-white">Entity Resolution Result (FollowTheMoney Standard)</span>
                      <span className="text-emerald-400 font-bold">Score: {queryResult.entityResolution.confidenceScore}%</span>
                    </div>
                    <div className="grid grid-cols-1 sm:grid-cols-2 gap-3">
                      <div className="p-3 bg-slate-900 rounded-xl border border-slate-800">
                        <span className="text-slate-400 text-[10px] block">Matched Canonical Entity ID</span>
                        <span className="text-amber-400 font-bold">{queryResult.entityResolution.matchedEntityId}</span>
                      </div>
                      <div className="p-3 bg-slate-900 rounded-xl border border-slate-800">
                        <span className="text-slate-400 text-[10px] block">Canonical Name</span>
                        <span className="text-emerald-400 font-bold">{queryResult.entityResolution.canonicalName}</span>
                      </div>
                    </div>
                  </div>
                )}

                {activeResultTab === "graph" && (
                  <div className="space-y-2">
                    <div className="flex justify-between items-center text-slate-400 pb-2 border-b border-slate-900 text-[11px]">
                      <span>Автогенерений Cypher запит для Neo4j / Memgraph</span>
                      <button
                        onClick={() => copyToClipboard(queryResult.graphDbCypher, "cypher")}
                        className="text-purple-400 hover:text-purple-300 flex items-center gap-1 cursor-pointer"
                      >
                        {copiedKey === "cypher" ? <Check className="w-3.5 h-3.5" /> : <Copy className="w-3.5 h-3.5" />}
                        <span>Копіювати Cypher</span>
                      </button>
                    </div>
                    <pre className="text-purple-300 leading-relaxed font-mono">
                      {queryResult.graphDbCypher}
                    </pre>
                  </div>
                )}

                {activeResultTab === "storage" && (
                  <div className="space-y-2 text-xs">
                    <div className="text-slate-400 text-[11px] pb-2 border-b border-slate-900">
                      Автоматичний розподіл результатів згідно з Storage Router:
                    </div>
                    <div className="p-2.5 bg-slate-900 rounded-xl border border-slate-800 flex justify-between">
                      <span className="text-slate-300">🐘 PostgreSQL:</span>
                      <span className="text-blue-400 font-bold">{queryResult.storageLocations.postgresql}</span>
                    </div>
                    <div className="p-2.5 bg-slate-900 rounded-xl border border-slate-800 flex justify-between">
                      <span className="text-slate-300">🕸️ Neo4j Graph:</span>
                      <span className="text-purple-400 font-bold">{queryResult.storageLocations.neo4jGraph}</span>
                    </div>
                    <div className="p-2.5 bg-slate-900 rounded-xl border border-slate-800 flex justify-between">
                      <span className="text-slate-300">📦 MinIO S3 Raw:</span>
                      <span className="text-amber-400 font-bold">{queryResult.storageLocations.minioS3}</span>
                    </div>
                    <div className="p-2.5 bg-slate-900 rounded-xl border border-slate-800 flex justify-between">
                      <span className="text-slate-300">📐 Qdrant Vector:</span>
                      <span className="text-emerald-400 font-bold">{queryResult.storageLocations.qdrantVector}</span>
                    </div>
                  </div>
                )}

                {activeResultTab === "quality" && (
                  <div className="space-y-3">
                    <div className="text-slate-400 text-[11px]">Результати автоматичного аудиту якості та лінеажності:</div>
                    <div className="grid grid-cols-2 gap-2 text-xs">
                      <div className="p-2.5 bg-slate-900 rounded-xl border border-slate-800">
                        <span className="text-slate-400 text-[10px] block">Перевірка дублікатів:</span>
                        <span className="text-emerald-400 font-bold">{queryResult.qualityAudit.duplicateCheck}</span>
                      </div>
                      <div className="p-2.5 bg-slate-900 rounded-xl border border-slate-800">
                        <span className="text-slate-400 text-[10px] block">Відсоток порожніх полів:</span>
                        <span className="text-emerald-400 font-bold">{queryResult.qualityAudit.nullsPercentage}</span>
                      </div>
                      <div className="p-2.5 bg-slate-900 rounded-xl border border-slate-800">
                        <span className="text-slate-400 text-[10px] block">Версія походження (Provenance):</span>
                        <span className="text-amber-400 font-bold">{queryResult.qualityAudit.provenanceVersion}</span>
                      </div>
                      <div className="p-2.5 bg-slate-900 rounded-xl border border-slate-800">
                        <span className="text-slate-400 text-[10px] block">Призначений Trust Score:</span>
                        <span className="text-emerald-400 font-bold">{queryResult.qualityAudit.trustScoreAssigned}%</span>
                      </div>
                    </div>
                  </div>
                )}
              </div>
            </motion.div>
          )}
        </AnimatePresence>
      </div>

      {/* UNIVERSAL DISCOVERY ENGINE PANEL (STAGE 8) */}
      <div className="p-5 bg-gradient-to-r from-indigo-950/50 via-slate-900 to-purple-950/50 border border-indigo-500/40 rounded-3xl space-y-4 shadow-xl">
        <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-3 border-b border-slate-800 pb-3">
          <div className="flex items-center gap-2">
            <Bot className="w-5 h-5 text-indigo-400" />
            <div>
              <h3 className="text-sm font-bold text-white uppercase tracking-wider font-mono">
                Universal Discovery Engine (Auto API & Schema Drift Control)
              </h3>
              <p className="text-[11px] text-slate-400">
                Автономно знаходить OpenAPI, GraphQL, SOAP, CKAN, OData, RSS, S3, MCP-сервери, будує Entity Mapping та контролює Schema Drift
              </p>
            </div>
          </div>
          <div className="flex items-center gap-2">
            <span className="px-2.5 py-1 bg-indigo-500/20 text-indigo-300 border border-indigo-500/40 rounded-full font-mono text-xs font-bold">
              Discovery Engine Active
            </span>
            <button
              type="button"
              onClick={() => {
                setSchemaDriftActive(!schemaDriftActive);
                showToast(`Schema Drift Control ${!schemaDriftActive ? "увімкнено" : "вимкнено"}`, "info");
              }}
              className={`px-2.5 py-1 rounded-full font-mono text-xs font-bold border transition-all cursor-pointer ${
                schemaDriftActive ? "bg-emerald-500/20 text-emerald-300 border-emerald-500/40" : "bg-slate-800 text-slate-400 border-slate-700"
              }`}
            >
              Schema Drift: {schemaDriftActive ? "Active ✓" : "Off"}
            </button>
          </div>
        </div>

        <form onSubmit={handleRunFactoryGenerator} className="grid grid-cols-1 md:grid-cols-12 gap-3">
          <div className="md:col-span-8">
            <label className="block text-[11px] font-mono text-slate-400 mb-1">URL OpenAPI, Swagger, CKAN чи WSDL будь-якого державного реєстру</label>
            <input
              type="text"
              value={factoryDocsUrl}
              onChange={(e) => setFactoryDocsUrl(e.target.value)}
              placeholder="https://data.gov.ua/api/3/action/package_show"
              className="w-full bg-slate-950 border border-slate-800 rounded-xl px-3 py-2 text-xs text-slate-200 focus:outline-none focus:border-indigo-500 font-mono"
            />
          </div>

          <div className="md:col-span-4 flex items-end">
            <button
              type="submit"
              disabled={isGeneratingConnector}
              className="w-full py-2 px-4 bg-indigo-600 hover:bg-indigo-500 disabled:opacity-50 text-white font-mono font-bold text-xs rounded-xl flex items-center justify-center gap-2 transition-all cursor-pointer shadow-lg shadow-indigo-950/50"
            >
              {isGeneratingConnector ? (
                <>
                  <RefreshCw className="w-4 h-4 animate-spin text-white" />
                  <span>ШІ Сканує API & Генерує...</span>
                </>
              ) : (
                <>
                  <Wand2 className="w-4 h-4 text-white" />
                  <span>Авто-згенерувати Конектор</span>
                </>
              )}
            </button>
          </div>
        </form>

        {generatedCode && (
          <motion.div initial={{ opacity: 0 }} animate={{ opacity: 1 }} className="space-y-2 pt-2">
            <div className="flex justify-between items-center text-xs text-indigo-300 font-mono">
              <span>Автогенерений TypeScript Код Конектора з Schema Drift Control & FollowTheMoney Mapping</span>
              <button
                onClick={() => copyToClipboard(generatedCode, "gen_code")}
                className="text-indigo-400 hover:text-indigo-300 flex items-center gap-1 cursor-pointer"
              >
                {copiedKey === "gen_code" ? <Check className="w-3.5 h-3.5" /> : <Copy className="w-3.5 h-3.5" />}
                <span>Копіювати код</span>
              </button>
            </div>
            <pre className="p-4 bg-slate-950 border border-slate-800 rounded-2xl text-indigo-300 font-mono text-xs overflow-x-auto max-h-60 custom-scrollbar">
              {generatedCode}
            </pre>
          </motion.div>
        )}
      </div>

      {/* FILTER & CONNECTORS CATALOG GRID */}
      <div className="space-y-4">
        <div className="flex flex-col md:flex-row md:items-center justify-between gap-3">
          <div className="flex items-center gap-1.5 overflow-x-auto pb-1">
            <button
              onClick={() => {
                setActiveStage("ALL");
                setActiveSubFilter("ALL");
              }}
              className={`px-3 py-1.5 rounded-xl text-xs font-bold transition-all cursor-pointer whitespace-nowrap ${
                activeStage === "ALL"
                  ? "bg-emerald-500 text-slate-950 font-black shadow-md"
                  : "bg-slate-900 border border-slate-800 text-slate-400 hover:text-white"
              }`}
            >
              Всі джерела ({connectors.length})
            </button>

            {STAGES_CONFIG.map((s) => (
              <button
                key={s.id}
                onClick={() => setActiveStage(s.id)}
                className={`px-3 py-1.5 rounded-xl text-xs font-bold transition-all cursor-pointer whitespace-nowrap ${
                  activeStage === s.id
                    ? "bg-amber-500 text-slate-950 font-black shadow-md"
                    : "bg-slate-900 border border-slate-800 text-slate-400 hover:text-white"
                }`}
              >
                {s.title.split("(")[0]}
              </button>
            ))}
          </div>

          <div className="relative w-full md:w-64">
            <Search className="w-4 h-4 absolute left-3 top-2.5 text-slate-500" />
            <input
              type="text"
              value={searchQuery}
              onChange={(e) => setSearchQuery(e.target.value)}
              placeholder="Пошук конекторів..."
              className="w-full bg-slate-900 border border-slate-800 rounded-xl pl-9 pr-3 py-1.5 text-xs text-slate-200 focus:outline-none focus:border-emerald-500 font-mono"
            />
          </div>
        </div>

        {/* Sub-category Wave Filter Bar */}
        <div className="flex items-center gap-1.5 font-mono text-[11px] overflow-x-auto pb-1">
          <span className="text-slate-500 font-bold mr-1">Друга Хвиля:</span>
          {[
            { id: "ALL", label: "Всі категорії" },
            { id: "CORE", label: "Core Registries" },
            { id: "CYBER", label: "Cyber Intel" },
            { id: "SCIENTIFIC", label: "Scientific Intel" },
            { id: "OSINT", label: "OSINT & Git" },
            { id: "GEOSPATIAL", label: "Geospatial" },
            { id: "FINANCIAL", label: "Financial Intel" },
          ].map((sub) => (
            <button
              key={sub.id}
              onClick={() => setActiveSubFilter(sub.id as any)}
              className={`px-2.5 py-1 rounded-lg border cursor-pointer transition-all ${
                activeSubFilter === sub.id
                  ? "bg-blue-500/20 text-blue-300 border-blue-500/40 font-bold"
                  : "bg-slate-950 border-slate-800 text-slate-400 hover:text-slate-200"
              }`}
            >
              {sub.label}
            </button>
          ))}
        </div>

        {/* Catalog Grid */}
        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4">
          {filteredConnectors.map((c) => (
            <motion.div
              key={c.id}
              layout
              className={`bg-slate-900/90 border rounded-3xl p-5 flex flex-col justify-between space-y-4 shadow-lg transition-all relative overflow-hidden group ${
                c.isCoreSeven
                  ? "border-amber-500/40 bg-gradient-to-b from-amber-950/20 via-slate-900 to-slate-900 shadow-amber-950/20"
                  : c.enabled
                  ? "border-slate-800/90 hover:border-slate-700"
                  : "border-rose-900/40 opacity-75"
              }`}
            >
              <div className="space-y-3">
                <div className="flex items-start justify-between gap-2">
                  <div className="flex items-center gap-2.5">
                    <span className="text-2xl p-2 bg-slate-950 rounded-2xl border border-slate-800">
                      {c.flag}
                    </span>
                    <div>
                      <h4 className="text-xs font-bold text-white group-hover:text-emerald-400 transition-colors leading-tight flex items-center gap-1.5">
                        <span>{c.name}</span>
                        {c.isCoreSeven && <Star className="w-3.5 h-3.5 text-amber-400 fill-amber-400 flex-shrink-0" />}
                      </h4>
                      <span className="text-[10px] text-slate-400 font-mono">{c.passport.owner}</span>
                    </div>
                  </div>

                  <span className={`px-2 py-0.5 rounded-full text-[10px] font-mono font-bold uppercase border bg-slate-950 ${
                    c.isCoreSeven ? "border-amber-500/50 text-amber-300" : "border-slate-800 text-slate-300"
                  }`}>
                    {c.stage.replace("_", " ")}
                  </span>
                </div>

                <p className="text-xs text-slate-300 leading-relaxed font-sans min-h-[38px]">
                  {c.description}
                </p>

                {/* Quick Passport Specs */}
                <div className="space-y-1.5 font-mono text-[11px] bg-slate-950/80 p-3 rounded-2xl border border-slate-800/80">
                  <div className="flex justify-between items-center text-slate-400">
                    <span>Тип доступу:</span>
                    <span className="text-slate-200 font-bold">{c.passport.accessType}</span>
                  </div>
                  <div className="flex justify-between items-center text-slate-400">
                    <span>Країна origin:</span>
                    <span className="text-slate-200">{c.passport.country}</span>
                  </div>
                  <div className="flex justify-between items-center text-slate-400">
                    <span>Trust Score:</span>
                    <span className="text-emerald-400 font-bold">{c.passport.trustScore}%</span>
                  </div>
                </div>
              </div>

              {/* Action Toolbar */}
              <div className="flex items-center gap-2 pt-2 border-t border-slate-800/80">
                <button
                  onClick={() => {
                    setSelectedConnectorId(c.id);
                    setQueryTerm(c.sampleQuery.split("=")[1] || "ТОВ Спеціальні Технології");
                    window.scrollTo({ top: 300, behavior: "smooth" });
                    handleExecuteQuery();
                  }}
                  className="flex-1 py-2 bg-emerald-600/20 hover:bg-emerald-600/30 text-emerald-300 border border-emerald-500/40 rounded-xl text-xs font-mono font-bold flex items-center justify-center gap-1.5 transition-all cursor-pointer"
                >
                  <Play className="w-3.5 h-3.5 fill-emerald-300" />
                  <span>Тест у консолі</span>
                </button>

                <button
                  onClick={() => setActivePassportConnector(c)}
                  className="p-2 bg-amber-500/20 hover:bg-amber-500/30 text-amber-300 border border-amber-500/40 rounded-xl transition-all flex items-center justify-center cursor-pointer"
                  title="Переглянути Паспорт Конектора"
                >
                  <FileText className="w-3.5 h-3.5" />
                </button>

                <button
                  onClick={() => toggleConnectorStatus(c.id)}
                  className={`p-2 rounded-xl transition-all flex items-center justify-center cursor-pointer ${
                    c.enabled ? "bg-slate-800 text-emerald-400 hover:bg-slate-700" : "bg-rose-900/30 text-rose-400 border border-rose-500/30"
                  }`}
                  title={c.enabled ? "Вимкнути конектор (Hot Reload)" : "Увімкнути конектор"}
                >
                  <PowerIcon enabled={c.enabled} />
                </button>
              </div>
            </motion.div>
          ))}
        </div>
      </div>

      {/* CONNECTOR PASSPORT MODAL (18 PARAMETERS) */}
      <AnimatePresence>
        {activePassportConnector && (
          <motion.div
            initial={{ opacity: 0 }}
            animate={{ opacity: 1 }}
            exit={{ opacity: 0 }}
            className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-slate-950/80 backdrop-blur-md"
          >
            <motion.div
              initial={{ scale: 0.95, opacity: 0 }}
              animate={{ scale: 1, opacity: 1 }}
              exit={{ scale: 0.95, opacity: 0 }}
              className="bg-slate-900 border border-slate-800 rounded-2xl p-3 sm:p-4 w-full w-full shadow-2xl space-y-5 overflow-y-auto max-h-[90vh] custom-scrollbar"
            >
              <div className="flex items-center justify-between border-b border-slate-800 pb-3">
                <div className="flex items-center gap-3">
                  <span className="text-3xl p-2 bg-slate-950 rounded-2xl border border-slate-800">
                    {activePassportConnector.flag}
                  </span>
                  <div>
                    <div className="flex items-center gap-2">
                      <span className="px-2 py-0.5 bg-amber-500/20 text-amber-300 border border-amber-500/40 rounded text-[10px] font-mono font-bold uppercase">
                        Технічний Паспорт Конектора
                      </span>
                      <span className="text-xs text-slate-400 font-mono">[{activePassportConnector.stage}]</span>
                    </div>
                    <h3 className="text-base font-bold text-white font-mono mt-0.5">
                      {activePassportConnector.name}
                    </h3>
                  </div>
                </div>
                <button
                  onClick={() => setActivePassportConnector(null)}
                  className="text-slate-400 hover:text-white p-1 cursor-pointer font-bold text-lg"
                >
                  ✕
                </button>
              </div>

              {/* 18-Parameter Passport Grid */}
              <div className="grid grid-cols-1 sm:grid-cols-2 gap-3 text-xs font-mono">
                <div className="p-3 bg-slate-950 rounded-2xl border border-slate-800 space-y-1">
                  <span className="text-slate-400 text-[10px] uppercase">1. Назва Джерела</span>
                  <div className="text-white font-bold">{activePassportConnector.name}</div>
                </div>

                <div className="p-3 bg-slate-950 rounded-2xl border border-slate-800 space-y-1">
                  <span className="text-slate-400 text-[10px] uppercase">2. Категорія</span>
                  <div className="text-emerald-400 font-bold">{activePassportConnector.category}</div>
                </div>

                <div className="p-3 bg-slate-950 rounded-2xl border border-slate-800 space-y-1">
                  <span className="text-slate-400 text-[10px] uppercase">3. Власник / Оператор</span>
                  <div className="text-slate-200">{activePassportConnector.passport.owner}</div>
                </div>

                <div className="p-3 bg-slate-950 rounded-2xl border border-slate-800 space-y-1">
                  <span className="text-slate-400 text-[10px] uppercase">4. Країна походження</span>
                  <div className="text-slate-200">{activePassportConnector.passport.country}</div>
                </div>

                <div className="p-3 bg-slate-950 rounded-2xl border border-slate-800 space-y-1">
                  <span className="text-slate-400 text-[10px] uppercase">5. Тип доступу</span>
                  <div className="text-blue-400 font-bold">{activePassportConnector.passport.accessType}</div>
                </div>

                <div className="p-3 bg-slate-950 rounded-2xl border border-slate-800 space-y-1">
                  <span className="text-slate-400 text-[10px] uppercase">6. Ліцензія використання</span>
                  <div className="text-purple-400 font-bold">{activePassportConnector.passport.license}</div>
                </div>

                <div className="p-3 bg-slate-950 rounded-2xl border border-slate-800 space-y-1">
                  <span className="text-slate-400 text-[10px] uppercase">7. Рівень Довіри (Trust Score)</span>
                  <div className="text-emerald-400 font-bold text-sm">{activePassportConnector.passport.trustScore}%</div>
                </div>

                <div className="p-3 bg-slate-950 rounded-2xl border border-slate-800 space-y-1">
                  <span className="text-slate-400 text-[10px] uppercase">8. Бізнес-цінність (Business Value)</span>
                  <div className="text-amber-400 font-bold text-sm">N/A</div>
                </div>

                <div className="p-3 bg-slate-950 rounded-2xl border border-slate-800 space-y-1">
                  <span className="text-slate-400 text-[10px] uppercase">9. Рівень ризику (Risk Rating)</span>
                  <div className="text-emerald-400 font-bold">N/A</div>
                </div>

                <div className="p-3 bg-slate-950 rounded-2xl border border-slate-800 space-y-1">
                  <span className="text-slate-400 text-[10px] uppercase">10. Повнота даних (Completeness)</span>
                  <div className="text-slate-200">N/A</div>
                </div>

                <div className="p-3 bg-slate-950 rounded-2xl border border-slate-800 space-y-1">
                  <span className="text-slate-400 text-[10px] uppercase">11. Частота оновлення</span>
                  <div className="text-slate-200">{activePassportConnector.passport.updateFreq || 'N/A'}</div>
                </div>

                <div className="p-3 bg-slate-950 rounded-2xl border border-slate-800 space-y-1">
                  <span className="text-slate-400 text-[10px] uppercase">12. Середня затримка (Latency)</span>
                  <div className="text-emerald-400 font-bold">N/A</div>
                </div>

                <div className="p-3 bg-slate-950 rounded-2xl border border-slate-800 space-y-1">
                  <span className="text-slate-400 text-[10px] uppercase">13. Кількість сутностей</span>
                  <div className="text-slate-200">N/A</div>
                </div>

                <div className="p-3 bg-slate-950 rounded-2xl border border-slate-800 space-y-1">
                  <span className="text-slate-400 text-[10px] uppercase">14. Кількість графових зв'язків</span>
                  <div className="text-purple-400 font-bold">N/A</div>
                </div>

                <div className="p-3 bg-slate-950 rounded-2xl border border-slate-800 space-y-1 sm:col-span-2">
                  <span className="text-slate-400 text-[10px] uppercase">15. Підтримувані формати даних</span>
                  <div className="flex flex-wrap gap-1.5 pt-1">
                    {activePassportConnector.passport.dataFormats?.map((dt) => (
                      <span key={dt} className="px-2 py-0.5 bg-slate-900 border border-slate-800 text-slate-300 rounded text-[10px]">
                        {dt}
                      </span>
                    )) || <span className="text-slate-500">N/A</span>}
                  </div>
                </div>

                <div className="p-3 bg-slate-950 rounded-2xl border border-slate-800 space-y-1 sm:col-span-2">
                  <span className="text-slate-400 text-[10px] uppercase">16. Вимоги авторизації</span>
                  <div className="flex flex-wrap gap-1.5 pt-1">
                    {activePassportConnector.passport.authProtocol ? (
                      <span className="px-2 py-0.5 bg-emerald-500/10 border border-emerald-500/30 text-emerald-300 rounded text-[10px] font-bold">
                        {activePassportConnector.passport.authProtocol}
                      </span>
                    ) : <span className="text-slate-500">N/A</span>}
                  </div>
                </div>

                <div className="p-3 bg-slate-950 rounded-2xl border border-slate-800 space-y-1">
                  <span className="text-slate-400 text-[10px] uppercase">17. Статус працездатності</span>
                  <div className="text-emerald-400 font-bold flex items-center gap-1.5">
                    <span className="w-2 h-2 rounded-full bg-emerald-400 animate-pulse" />
                    <span>N/A</span>
                  </div>
                </div>

                <div className="p-3 bg-slate-950 rounded-2xl border border-slate-800 space-y-1">
                  <span className="text-slate-400 text-[10px] uppercase">18. AI Priority Score</span>
                  <div className="text-indigo-400 font-bold text-sm">N/A</div>
                </div>
              </div>

              <div className="flex justify-end gap-2 pt-2 border-t border-slate-800">
                <button
                  onClick={() => setActivePassportConnector(null)}
                  className="px-4 py-2 bg-slate-800 hover:bg-slate-700 text-slate-200 rounded-xl text-xs font-bold font-mono cursor-pointer"
                >
                  Закрити паспорт
                </button>
              </div>
            </motion.div>
          </motion.div>
        )}
      </AnimatePresence>

      {/* UNIVERSAL AUTH MANAGER CONFIGURATION MODAL */}
      <AnimatePresence>
        {authConfigModal && (
          <motion.div
            initial={{ opacity: 0 }}
            animate={{ opacity: 1 }}
            exit={{ opacity: 0 }}
            className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-slate-950/80 backdrop-blur-md"
          >
            <motion.div
              initial={{ scale: 0.95, opacity: 0 }}
              animate={{ scale: 1, opacity: 1 }}
              exit={{ scale: 0.95, opacity: 0 }}
              className="bg-slate-900 border border-slate-800 rounded-2xl p-3 sm:p-4 w-full w-full shadow-2xl space-y-4 font-mono text-xs"
            >
              <div className="flex items-center justify-between border-b border-slate-800 pb-3">
                <div className="flex items-center gap-2">
                  <Key className="w-5 h-5 text-amber-400" />
                  <h3 className="text-sm font-bold text-white uppercase tracking-wider">
                    Universal Auth Manager (Vault Configuration)
                  </h3>
                </div>
                <button
                  onClick={() => setAuthConfigModal(false)}
                  className="text-slate-400 hover:text-white p-1 cursor-pointer font-bold"
                >
                  ✕
                </button>
              </div>

              <div className="space-y-3">
                <div>
                  <label className="block text-slate-300 mb-1">Протокол авторизації</label>
                  <select
                    value={selectedAuthProtocol}
                    onChange={(e) => setSelectedAuthProtocol(e.target.value)}
                    className="w-full bg-slate-950 border border-slate-800 rounded-xl px-3 py-2 text-slate-200 focus:outline-none focus:border-amber-500"
                  >
                    {["API Key", "OAuth2", "JWT", "Bearer Token", "Basic Auth", "Cookie / Session", "Personal Access Token", "Client Secret", "mTLS", "SSH Keys"].map((m) => (
                      <option key={m} value={m}>
                        {m}
                      </option>
                    ))}
                  </select>
                </div>

                <div>
                  <label className="block text-slate-300 mb-1">Ключ / Токен / Секрет</label>
                  <input
                    type="password"
                    placeholder="Введіть приватне значення для Vault..."
                    className="w-full bg-slate-950 border border-slate-800 rounded-xl px-3 py-2 text-slate-200 focus:outline-none focus:border-amber-500"
                  />
                </div>

                <div className="p-3 bg-amber-500/10 border border-amber-500/20 rounded-xl text-amber-300 text-[11px]">
                  💡 Всі ключі шифруються за допомогою AES-256 GCM у локальному ізольованому Vault та не виходять за межі вашого оточення.
                </div>
              </div>

              <div className="flex justify-end gap-2 pt-2 border-t border-slate-800">
                <button
                  onClick={() => setAuthConfigModal(false)}
                  className="px-4 py-2 bg-slate-800 hover:bg-slate-700 text-slate-300 rounded-xl text-xs font-bold cursor-pointer"
                >
                  Скасувати
                </button>
                <button
                  onClick={() => {
                    showToast("Конфігурація авторизації збережена у Vault", "success");
                    setAuthConfigModal(false);
                  }}
                  className="px-4 py-2 bg-amber-600 hover:bg-amber-500 text-white rounded-xl text-xs font-bold cursor-pointer"
                >
                  Зберегти у Vault
                </button>
              </div>
            </motion.div>
          </motion.div>
        )}
      </AnimatePresence>
    </div>
  );
}

function PowerIcon({ enabled: _enabled }: { enabled: boolean }) {
  return (
    <svg className="w-3.5 h-3.5" fill="none" viewBox="0 0 24 24" stroke="currentColor">
      <path
        strokeLinecap="round"
        strokeLinejoin="round"
        strokeWidth={2}
        d="M13 10V3L4 14h7v7l9-11h-7z"
      />
    </svg>
  );
}
