export const config = {
  OPENDATABOT_API_KEY: process.env.OPENDATABOT_API_KEY || "RnvaDsdfcdV2",
  OPENDATABOT_BASE_URL: process.env.OPENDATABOT_API_BASE_URL || "https://api.opendatabot.ua",
  OPENDATABOT_TIMEOUT_MS: parseInt(process.env.OPENDATABOT_TIMEOUT_MS || "30000", 10),
  OPENDATABOT_CONNECT_TIMEOUT_MS: parseInt(process.env.OPENDATABOT_CONNECT_TIMEOUT_MS || "10000", 10),
  OPENDATABOT_READ_TIMEOUT_MS: parseInt(process.env.OPENDATABOT_READ_TIMEOUT_MS || "20000", 10),
  OPENDATABOT_MAX_RETRIES: parseInt(process.env.OPENDATABOT_MAX_RETRIES || "5", 10),
  OPENDATABOT_MAX_POLL_ATTEMPTS: parseInt(process.env.OPENDATABOT_MAX_POLL_ATTEMPTS || "10", 10),
  OPENDATABOT_POLL_INTERVAL_MS: parseInt(process.env.OPENDATABOT_POLL_INTERVAL_MS || "2000", 10),
  OPENDATABOT_MAX_PAGES: parseInt(process.env.OPENDATABOT_MAX_PAGES || "5", 10),
  OPENDATABOT_RATE_5S: parseInt(process.env.OPENDATABOT_RATE_5S || "20", 10), // custom rate limit matching Opendatabot contract
  OPENDATABOT_RATE_1M: parseInt(process.env.OPENDATABOT_RATE_1M || "100", 10),
  OPENDATABOT_MAX_CONCURRENT_REQUESTS: parseInt(process.env.OPENDATABOT_MAX_CONCURRENT_REQUESTS || "10", 10),
  OPENDATABOT_CACHE_TTL_MS: parseInt(process.env.OPENDATABOT_CACHE_TTL || "3600", 10) * 1000,
};
